name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: bash ./.github/scripts/myscript.sh
      shell: bash

