name: Upload Website

on:
  push:
    branches:
    - main

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: Run the script file
         run: sh ./github/scripts/myscript.sh
